blank_issues_enabled: true
contact_links:
  - name: ğŸ’¬ Preguntas y Discusiones
    url: https://github.com/Enzo008/saas-template/discussions
    about: Haz preguntas o inicia discusiones sobre el proyecto
  - name: ğŸ“š DocumentaciÃ³n
    url: https://github.com/Enzo008/saas-template#readme
    about: Lee la documentaciÃ³n completa del proyecto
  - name: ğŸš€ Demo en Vivo
    url: http://powermas-001-site4.atempurl.com/
    about: Prueba la aplicaciÃ³n en vivo
